<?php
/**
 * MerchantsApi
 * PHP version 7.3
 *
 * @category Class
 * @package  ClearentIntegrationsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Integrations API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClearentIntegrationsApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ClearentIntegrationsApi\ApiException;
use ClearentIntegrationsApi\Configuration;
use ClearentIntegrationsApi\HeaderSelector;
use ClearentIntegrationsApi\ObjectSerializer;

/**
 * MerchantsApi Class Doc Comment
 *
 * @category Class
 * @package  ClearentIntegrationsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MerchantsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation createMerchant
     *
     * @param  string $hierarchy_node_key hierarchy_node_key (required)
     * @param  \ClearentIntegrationsApi\Model\CreateMerchantPayload $create_merchant_payload create_merchant_payload (required)
     *
     * @throws \ClearentIntegrationsApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ClearentIntegrationsApi\Model\CreateMerchantResponse
     */
    public function createMerchant($hierarchy_node_key, $create_merchant_payload)
    {
        list($response) = $this->createMerchantWithHttpInfo($hierarchy_node_key, $create_merchant_payload);
        return $response;
    }

    /**
     * Operation createMerchantWithHttpInfo
     *
     * @param  string $hierarchy_node_key (required)
     * @param  \ClearentIntegrationsApi\Model\CreateMerchantPayload $create_merchant_payload (required)
     *
     * @throws \ClearentIntegrationsApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ClearentIntegrationsApi\Model\CreateMerchantResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function createMerchantWithHttpInfo($hierarchy_node_key, $create_merchant_payload)
    {
        $request = $this->createMerchantRequest($hierarchy_node_key, $create_merchant_payload);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 201:
                    if ('\ClearentIntegrationsApi\Model\CreateMerchantResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ClearentIntegrationsApi\Model\CreateMerchantResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ClearentIntegrationsApi\Model\CreateMerchantResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ClearentIntegrationsApi\Model\CreateMerchantResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 201:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClearentIntegrationsApi\Model\CreateMerchantResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation createMerchantAsync
     *
     * @param  string $hierarchy_node_key (required)
     * @param  \ClearentIntegrationsApi\Model\CreateMerchantPayload $create_merchant_payload (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMerchantAsync($hierarchy_node_key, $create_merchant_payload)
    {
        return $this->createMerchantAsyncWithHttpInfo($hierarchy_node_key, $create_merchant_payload)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation createMerchantAsyncWithHttpInfo
     *
     * @param  string $hierarchy_node_key (required)
     * @param  \ClearentIntegrationsApi\Model\CreateMerchantPayload $create_merchant_payload (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function createMerchantAsyncWithHttpInfo($hierarchy_node_key, $create_merchant_payload)
    {
        $returnType = '\ClearentIntegrationsApi\Model\CreateMerchantResponse';
        $request = $this->createMerchantRequest($hierarchy_node_key, $create_merchant_payload);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'createMerchant'
     *
     * @param  string $hierarchy_node_key (required)
     * @param  \ClearentIntegrationsApi\Model\CreateMerchantPayload $create_merchant_payload (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function createMerchantRequest($hierarchy_node_key, $create_merchant_payload)
    {
        // verify the required parameter 'hierarchy_node_key' is set
        if ($hierarchy_node_key === null || (is_array($hierarchy_node_key) && count($hierarchy_node_key) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $hierarchy_node_key when calling createMerchant'
            );
        }
        // verify the required parameter 'create_merchant_payload' is set
        if ($create_merchant_payload === null || (is_array($create_merchant_payload) && count($create_merchant_payload) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $create_merchant_payload when calling createMerchant'
            );
        }

        $resourcePath = '/api/launchIntegratorSetup/v1.0/integrateMerchant/{hierarchyNodeKey}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // path params
        if ($hierarchy_node_key !== null) {
            $resourcePath = str_replace(
                '{' . 'hierarchyNodeKey' . '}',
                ObjectSerializer::toPathValue($hierarchy_node_key),
                $resourcePath
            );
        }


        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/json']
            );
        }

        // for model (json/xml)
        if (isset($create_merchant_payload)) {
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($create_merchant_payload));
            } else {
                $httpBody = $create_merchant_payload;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('AccessKey');
        if ($apiKey !== null) {
            $headers['AccessKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
