---
components:
  parameters:
    hierarchyNodeKeyParam:
      example: '4788000000000009'
      in: path
      name: hierarchyNodeKey
      required: true
      schema:
        type: string
  schemas:
    CreateMerchantPayload:
      additionalProperties: false
      properties:
        merchantInformation:
          $ref: '#/components/schemas/MerchantInformation'
        salesProfile:
          $ref: '#/components/schemas/SalesProfile'
      required:
        - merchantInformation
        - salesProfile
      type: object
    CreateMerchantResponse:
      additionalProperties: false
      properties:
        applicationURL:
          $ref: '#/components/schemas/applicationURL'
        merchant:
          additionalProperties: false
          properties:
            merchantInformation:
              additionalProperties: false
              properties:
                merchantNumber:
                  $ref: '#/components/schemas/merchantNumber'
              type: object
          type: object
        metadata:
          additionalProperties: false
          properties:
            timestamp:
              $ref: '#/components/schemas/timestamp'
          required:
            - timestamp
          type: object
      type: object
    MerchantInformation:
      additionalProperties: false
      properties:
        dbaName:
          $ref: '#/components/schemas/dbaName'
        emailAddress:
          $ref: '#/components/schemas/emailAddress'
      required:
        - dbaName
        - emailAddress
      type: object
    SalesProfile:
      additionalProperties: false
      properties:
        mccCode:
          $ref: '#/components/schemas/mccCode'
      required:
        - mccCode
      type: object
    applicationURL:
      example: https://boarding-sb.clearent.net/launch-integrator-setup/merchant/680eccd8-5836-410d-a632-ffad378e3ee9
      type: string
    dbaName:
      description: The publicly facing name of the business.
      example: Pizza and Joints Family Restaurant
      type: string
    emailAddress:
      description: The email address of the business.
      example: tphillips@dentalintel.com
      type: string
    mccCode:
      description: The Merchant Category Code (MCC) of the merchant. The MCC is a 4-digit number used to classify merchants and businesses by the type of goods or services provided.
      example: '8021'
      type: string
    merchantNumber:
      description: The number that identifies the merchant within the Clearent system.
      example: '8582949932024942'
      type: string
    timestamp:
      example: '2022-05-20T20:10:21.4787044Z'
      type: string
  securitySchemes:
    AccessKeyAuth:
      in: header
      name: AccessKey
      type: apiKey
info:
  license:
    name: Unlicensed
  title: Clearent Integrations API
  version: 1.0.0
openapi: 3.0.2
paths:
  /api/launchIntegratorSetup/v1.0/integrateMerchant/{hierarchyNodeKey}:
    post:
      operationId: createMerchant
      parameters:
        - $ref: '#/components/parameters/hierarchyNodeKeyParam'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateMerchantPayload'
        required: true
      responses:
        '201':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateMerchantResponse'
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      tags:
        - Merchants
security:
  - AccessKeyAuth: []
servers:
  - url: https://boarding-sb.clearent.net
  - url: https://boarding.clearent.net
tags:
  - name: Merchants