---
components:
  schemas:
    Business:
      properties:
        businessID:
          $ref: '#/components/schemas/businessID'
    BusinessPhone:
      properties:
        areaCode:
          type: string
        extension:
          type: string
        phoneNumber:
          type: string
        phoneTypeCodeID:
          type: integer
    SalesInformation:
      properties:
        assignedUser:
          type: integer
        businessID:
          type: integer
        compensationType:
          type: integer
        referralPartner:
          type: string
    SeasonalSchedule:
      properties:
        april:
          type: boolean
        august:
          type: boolean
        december:
          type: boolean
        february:
          type: boolean
        january:
          type: boolean
        july:
          type: boolean
        june:
          type: boolean
        march:
          type: boolean
        may:
          type: boolean
        november:
          type: boolean
        october:
          type: boolean
        september:
          type: boolean
    acceptsPaperStatements:
      type: boolean
    acceptsPaperTaxForms:
      type: boolean
    businessID:
      type: integer
    companyTypeId:
      type: integer
    dbaName:
      type: string
    emailAddress:
      type: string
    hierarchyNodeKey:
      type: string
    merchantNumber:
      type: string
    webSite:
      type: string
  securitySchemes:
    AccessKeyAuth:
      in: header
      name: AccessKey
      type: apiKey
info:
  title: Clearent Merchants API
  version: '1.0'
openapi: 3.0.2
paths:
  /api/demographics/v1.0/Merchants:
    get:
      operationId: getBoardingMerchants
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      tags:
        - Merchants
security:
  - AccessKeyAuth: []
servers:
  - url: https://boarding-sb.clearent.net
  - url: https://boarding.clearent.net
tags:
  - name: Merchants