<?php
/**
 * MerchantsApiTest
 * PHP version 7.3
 *
 * @category Class
 * @package  ClearentIntegrationsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Integrations API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.0.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClearentIntegrationsApi\Test\Api;

use \ClearentIntegrationsApi\Configuration;
use \ClearentIntegrationsApi\ApiException;
use \ClearentIntegrationsApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * MerchantsApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClearentIntegrationsApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MerchantsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createMerchant
     *
     * .
     *
     */
    public function testCreateMerchant()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
