name: Release Tag Updater

on:
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  release_tag_updater:
    runs-on: ubuntu-latest

    steps:
      - name: Create A New Release Tag
        uses: sersoft-gmbh/running-release-tags-action@v1
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
