# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  swagger_validation:
    runs-on: ubuntu-latest
    
    services:
      swagger-editor:
        image: swaggerapi/swagger-editor
        ports:
          - 80:8080

    steps:
      - uses: actions/checkout@v3

      - name: Validate OpenAPI definition - transactions
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: transactions.yaml

      - name: Validate OpenAPI definition - integration
        uses: char0n/swagger-editor-validate@v1
        with:
          swagger-editor-url: http://localhost/
          definition-file: integration.yaml